apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: ${{values.description | dump}}
  annotations:
  backstage.io/techdocs-ref: value
spec:
  type: documentation
  lifecycle: experimental
  owner: ${{values.owner | dump}}
